# NumPy

In [ ]:
import numpy as np

## Crear Arreglos de diferentes dimensiones

In [ ]:
value = 10 #rank 0
value_as_array = np.array(value)

value_as_array

array(10)

In [ ]:
value = [21, 83, 42, 35] #rank 1
value_as_array = np.array(value)

value_as_array

array([21, 83, 42, 35])

In [ ]:
value = [[21, 83, 42],
         [35, 12, 67]] #rank 2
value_as_array = np.array(value)

value_as_array

array([[21, 83, 42],
       [35, 12, 67]])

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ] #rank 3
value_as_array = np.array(value)

value_as_array

array([[[21, 83, 42],
        [35, 12, 67]],

       [[56, 98, 24],
        [64, 78, 98]]])

## Atributos de los Arreglos

In [ ]:
value = [[21, 83, 42],
         [35, 12, 67]]
value_as_array = np.array(value)

In [ ]:
#Number of axes
value_as_array.ndim

2

In [ ]:
#Length (number of elements) of each of the axes of a Tensor
value_as_array.shape

(2, 3)

In [ ]:
#Type of every element in the Tensor
value_as_array.dtype

dtype('int64')

## Operaciones con Arreglos

In [ ]:
value_1 = [[21, 83],
           [42, 35]]
value_2 = [[95, 78],
           [65, 32]]

array_1 = np.array(value_1)
array_2 = np.array(value_2)

### Suma

In [ ]:
np.add(array_1, array_2)

array([[116, 161],
       [107,  67]])

In [ ]:
array_1 + array_2

array([[116, 161],
       [107,  67]])

### Resta

In [ ]:
np.subtract(array_1, array_2)

array([[-74,   5],
       [-23,   3]])

In [ ]:
array_1 - array_2

array([[-74,   5],
       [-23,   3]])

### Multiplicación de elementos

In [ ]:
np.multiply(array_1, array_2)

array([[1995, 6474],
       [2730, 1120]])

In [ ]:
array_1 * array_2

array([[1995, 6474],
       [2730, 1120]])

### Multiplicación de matrices

In [ ]:
np.matmul(array_1, array_2)

array([[7390, 4294],
       [6265, 4396]])

In [ ]:
array_1 @ array_2

array([[7390, 4294],
       [6265, 4396]])

## Obtener la transpuesta

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

In [ ]:
np.transpose(value_as_array)

array([[[21, 56],
        [35, 64]],

       [[83, 98],
        [12, 78]],

       [[42, 24],
        [67, 98]]])

In [ ]:
value_as_array.T

array([[[21, 56],
        [35, 64]],

       [[83, 98],
        [12, 78]],

       [[42, 24],
        [67, 98]]])

## Obtener la inversa

In [ ]:
value = [[21, 83],
         [35, 12]]
value_as_array = np.array(value, dtype=np.float32)

In [ ]:
np.linalg.inv(value_as_array)

array([[-0.00452318,  0.03128534],
       [ 0.01319261, -0.00791557]], dtype=float32)

## Obtener la cantidad de elementos

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

In [ ]:
np.size(value_as_array)

12

In [ ]:
value_as_array.size

12

## Obtener el mayor elemento

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

In [ ]:
np.max(value_as_array, axis=0)

array([[56, 98, 42],
       [64, 78, 98]])

In [ ]:
np.max(value_as_array, axis=1)

array([[35, 83, 67],
       [64, 98, 98]])

In [ ]:
np.max(value_as_array, axis=2)

array([[83, 67],
       [98, 98]])

In [ ]:
np.max(value_as_array, axis=-1) #-1: last_possible_axis

array([[83, 67],
       [98, 98]])

## Obtener el índice del mayor elemento

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

In [ ]:
#56>21, 98>83, 42>24
#64>35, 78>12, 98>67
np.argmax(value_as_array, axis=0)

array([[1, 1, 0],
       [1, 1, 1]])

In [ ]:
#35>21, 83>12, 67>42
#64>56, 98>78, 98>24
np.argmax(value_as_array, axis=1)

array([[1, 0, 1],
       [1, 0, 1]])

In [ ]:
#83>42>21, 67>35>12
#98>56>24, 98>78>64
np.argmax(value_as_array, axis=2)

array([[1, 2],
       [1, 2]])

In [ ]:
np.argmax(value_as_array, axis=-1) #-1: last_possible_axis

array([[1, 2],
       [1, 2]])

## Indexación

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

In [ ]:
value_as_array[0]

array([[21, 83, 42],
       [35, 12, 67]])

In [ ]:
value_as_array[1]

array([[56, 98, 24],
       [64, 78, 98]])

In [ ]:
value_as_array[0:1]

array([[[21, 83, 42],
        [35, 12, 67]]])

In [ ]:
value_as_array[1:2]

array([[[56, 98, 24],
        [64, 78, 98]]])

In [ ]:
value_as_array[0, 0]

array([21, 83, 42])

In [ ]:
value_as_array[0, 1]

array([35, 12, 67])

In [ ]:
value_as_array[:, 0]

array([[21, 83, 42],
       [56, 98, 24]])

In [ ]:
value_as_array[:, 1]

array([[35, 12, 67],
       [64, 78, 98]])

In [ ]:
value_as_array[0, 0, 0]

21

In [ ]:
value_as_array[0, 0, 1]

83

In [ ]:
value_as_array[0, 0, 2]

42

In [ ]:
value_as_array[:, :, 0]

array([[21, 35],
       [56, 64]])

In [ ]:
value_as_array[:, :, 1]

array([[83, 12],
       [98, 78]])

In [ ]:
value_as_array[:, :, 2]

array([[42, 67],
       [24, 98]])

## Manipulando *Shapes*

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

value_as_array.shape

(2, 2, 3)

In [ ]:
np.reshape(value_as_array, (12,))

array([21, 83, 42, 35, 12, 67, 56, 98, 24, 64, 78, 98])

In [ ]:
np.reshape(value_as_array, (2, 6))

array([[21, 83, 42, 35, 12, 67],
       [56, 98, 24, 64, 78, 98]])

In [ ]:
np.reshape(value_as_array, (4, 3))

array([[21, 83, 42],
       [35, 12, 67],
       [56, 98, 24],
       [64, 78, 98]])

In [ ]:
np.reshape(value_as_array, (3, 4))

array([[21, 83, 42, 35],
       [12, 67, 56, 98],
       [24, 64, 78, 98]])

In [ ]:
np.reshape(value_as_array, (-1,))

array([21, 83, 42, 35, 12, 67, 56, 98, 24, 64, 78, 98])

In [ ]:
np.reshape(value_as_array, (3, -1))

array([[21, 83, 42, 35],
       [12, 67, 56, 98],
       [24, 64, 78, 98]])

## Convertir Arreglos a Listas

In [ ]:
value = [21, 83, 42, 35]
value_as_array = np.array(value)

In [ ]:
value_as_array.tolist()

[21, 83, 42, 35]

In [ ]:
list(value_as_array)

[21, 83, 42, 35]

# TensorFlow

In [ ]:
import tensorflow as tf
import numpy as np

## Crear Tensores de diferentes dimensiones

In [ ]:
value = 10 #rank 0
value_as_tensor = tf.convert_to_tensor(value)

value_as_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
value = [21, 83, 42, 35] #rank 1
value_as_tensor = tf.convert_to_tensor(value)

value_as_tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([21, 83, 42, 35], dtype=int32)>

In [ ]:
value = [[21, 83, 42],
         [35, 12, 67]] #rank 2
value_as_tensor = tf.convert_to_tensor(value)

value_as_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[21, 83, 42],
       [35, 12, 67]], dtype=int32)>

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ] #rank 3
value_as_tensor = tf.convert_to_tensor(value)

value_as_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[21, 83, 42],
        [35, 12, 67]],

       [[56, 98, 24],
        [64, 78, 98]]], dtype=int32)>

## Atributos de los tensores

In [ ]:
value = [[21, 83, 42],
         [35, 12, 67]]
value_as_tensor = tf.convert_to_tensor(value)

In [ ]:
#Number of axes
value_as_tensor.ndim

2

In [ ]:
#Length (number of elements) of each of the axes of a Tensor
value_as_tensor.shape

TensorShape([2, 3])

In [ ]:
#Type of every element in the Tensor
value_as_tensor.dtype

tf.int32

## Operaciones con Tensores

In [ ]:
value_1 = [[21, 83],
           [42, 35]]
value_2 = [[95, 78],
           [65, 32]]

tensor_1 = tf.convert_to_tensor(value_1)
tensor_2 = tf.convert_to_tensor(value_2)

### Suma

In [ ]:
tf.add(tensor_1, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[116, 161],
       [107,  67]], dtype=int32)>

In [ ]:
tensor_1 + tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[116, 161],
       [107,  67]], dtype=int32)>

### Resta

In [ ]:
tf.subtract(tensor_1, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-74,   5],
       [-23,   3]], dtype=int32)>

In [ ]:
tensor_1 - tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-74,   5],
       [-23,   3]], dtype=int32)>

### Multiplicación de elementos

In [ ]:
tf.multiply(tensor_1, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1995, 6474],
       [2730, 1120]], dtype=int32)>

In [ ]:
tensor_1 * tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1995, 6474],
       [2730, 1120]], dtype=int32)>

### Multiplicación de matrices

In [ ]:
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7390, 4294],
       [6265, 4396]], dtype=int32)>

In [ ]:
tensor_1 @ tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7390, 4294],
       [6265, 4396]], dtype=int32)>

## Obtener la transpuesta

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = tf.convert_to_tensor(value)

In [ ]:
tf.transpose(value_as_tensor)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[21, 56],
        [35, 64]],

       [[83, 98],
        [12, 78]],

       [[42, 24],
        [67, 98]]], dtype=int32)>

## Obtener la inversa

In [ ]:
value = [[21, 83],
         [35, 12]]
value_as_tensor = tf.convert_to_tensor(value, dtype=tf.float32)

In [ ]:
tf.linalg.inv(value_as_tensor)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00452318,  0.03128534],
       [ 0.01319261, -0.00791557]], dtype=float32)>

## Obtener la cantidad de elementos

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = tf.convert_to_tensor(value)

tf.size(value_as_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

## Obtener el mayor elemento

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = tf.convert_to_tensor(value)

In [ ]:
tf.reduce_max(value_as_tensor, axis=0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[56, 98, 42],
       [64, 78, 98]], dtype=int32)>

In [ ]:
tf.reduce_max(value_as_tensor, axis=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[35, 83, 67],
       [64, 98, 98]], dtype=int32)>

In [ ]:
tf.reduce_max(value_as_tensor, axis=2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[83, 67],
       [98, 98]], dtype=int32)>

In [ ]:
tf.reduce_max(value_as_tensor, axis=-1) #-1: last_possible_axis

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[83, 67],
       [98, 98]], dtype=int32)>

## Obtener el índice del mayor elemento

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = tf.convert_to_tensor(value)

In [ ]:
#56>21, 98>83, 42>24
#64>35, 78>12, 98>67
tf.argmax(value_as_tensor, axis=0)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 0],
       [1, 1, 1]])>

In [ ]:
#35>21, 83>12, 67>42
#64>56, 98>78, 98>24
tf.argmax(value_as_tensor, axis=1)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 0, 1],
       [1, 0, 1]])>

In [ ]:
#83>42>21, 67>35>12
#98>56>24, 98>78>64
tf.argmax(value_as_tensor, axis=2)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [1, 2]])>

In [ ]:
tf.argmax(value_as_tensor, axis=-1) #-1: last_possible_axis

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [1, 2]])>

## Indexación

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = tf.convert_to_tensor(value)

In [ ]:
value_as_tensor[0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[21, 83, 42],
       [35, 12, 67]], dtype=int32)>

In [ ]:
value_as_tensor[1]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[56, 98, 24],
       [64, 78, 98]], dtype=int32)>

In [ ]:
value_as_tensor[0:1]

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[21, 83, 42],
        [35, 12, 67]]], dtype=int32)>

In [ ]:
value_as_tensor[1:2]

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[56, 98, 24],
        [64, 78, 98]]], dtype=int32)>

In [ ]:
value_as_tensor[0, 0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([21, 83, 42], dtype=int32)>

In [ ]:
value_as_tensor[0, 1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([35, 12, 67], dtype=int32)>

In [ ]:
value_as_tensor[:, 0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[21, 83, 42],
       [56, 98, 24]], dtype=int32)>

In [ ]:
value_as_tensor[:, 1]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[35, 12, 67],
       [64, 78, 98]], dtype=int32)>

In [ ]:
value_as_tensor[0, 0, 0]

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [ ]:
value_as_tensor[0, 0, 1]

<tf.Tensor: shape=(), dtype=int32, numpy=83>

In [ ]:
value_as_tensor[0, 0, 2]

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
value_as_tensor[:, :, 0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 35],
       [56, 64]], dtype=int32)>

In [ ]:
value_as_tensor[:, :, 1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[83, 12],
       [98, 78]], dtype=int32)>

In [ ]:
value_as_tensor[:, :, 2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 67],
       [24, 98]], dtype=int32)>

## Manipulando *Shapes*

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = tf.convert_to_tensor(value)

value_as_tensor.shape

TensorShape([2, 2, 3])

In [ ]:
tf.reshape(value_as_tensor, (12,))

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([21, 83, 42, 35, 12, 67, 56, 98, 24, 64, 78, 98], dtype=int32)>

In [ ]:
tf.reshape(value_as_tensor, (2, 6))

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[21, 83, 42, 35, 12, 67],
       [56, 98, 24, 64, 78, 98]], dtype=int32)>

In [ ]:
tf.reshape(value_as_tensor, (4, 3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[21, 83, 42],
       [35, 12, 67],
       [56, 98, 24],
       [64, 78, 98]], dtype=int32)>

In [ ]:
tf.reshape(value_as_tensor, (3, 4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[21, 83, 42, 35],
       [12, 67, 56, 98],
       [24, 64, 78, 98]], dtype=int32)>

In [ ]:
tf.reshape(value_as_tensor, (-1,))

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([21, 83, 42, 35, 12, 67, 56, 98, 24, 64, 78, 98], dtype=int32)>

In [ ]:
tf.reshape(value_as_tensor, (3, -1))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[21, 83, 42, 35],
       [12, 67, 56, 98],
       [24, 64, 78, 98]], dtype=int32)>

## Convertir Tensores a NumPy array

In [ ]:
value = [21, 83, 42, 35]
value_as_tensor = tf.convert_to_tensor(value)

In [ ]:
value_as_tensor.numpy()

array([21, 83, 42, 35], dtype=int32)

In [ ]:
np.array(value_as_tensor)

array([21, 83, 42, 35], dtype=int32)

# PyTorch

In [ ]:
import torch
import numpy as np

## Crear Tensores de diferentes dimensiones

In [ ]:
value = 10 #rank 0
value_as_tensor = torch.tensor(value)

value_as_tensor

tensor(10)

In [ ]:
value = [21, 83, 42, 35] #rank 1
value_as_tensor = torch.tensor(value)

value_as_tensor

tensor([21, 83, 42, 35])

In [ ]:
value = [[21, 83, 42],
         [35, 12, 67]] #rank 2
value_as_tensor = torch.tensor(value)

value_as_tensor

tensor([[21, 83, 42],
        [35, 12, 67]])

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ] #rank 3
value_as_tensor = torch.tensor(value)

value_as_tensor

tensor([[[21, 83, 42],
         [35, 12, 67]],

        [[56, 98, 24],
         [64, 78, 98]]])

## Atributos de los tensores

In [ ]:
value = [[21, 83, 42],
         [35, 12, 67]]
value_as_tensor = torch.tensor(value)

In [ ]:
#Number of axes
value_as_tensor.ndim

2

In [ ]:
#Length (number of elements) of each of the axes of a Tensor
value_as_tensor.shape

torch.Size([2, 3])

In [ ]:
#Type of every element in the Tensor
value_as_tensor.dtype

torch.int64

## Operaciones con Tensores

In [ ]:
value_1 = [[21, 83],
           [42, 35]]
value_2 = [[95, 78],
           [65, 32]]

tensor_1 = torch.tensor(value_1)
tensor_2 = torch.tensor(value_2)

### Suma

In [ ]:
tensor_1.add(tensor_2)

tensor([[116, 161],
        [107,  67]])

In [ ]:
tensor_1 + tensor_2

tensor([[116, 161],
        [107,  67]])

### Resta

In [ ]:
tensor_1.subtract(tensor_2)

tensor([[-74,   5],
        [-23,   3]])

In [ ]:
tensor_1 - tensor_2

tensor([[-74,   5],
        [-23,   3]])

### Multiplicación de elementos

In [ ]:
tensor_1.multiply(tensor_2)

tensor([[1995, 6474],
        [2730, 1120]])

In [ ]:
tensor_1 * tensor_2

tensor([[1995, 6474],
        [2730, 1120]])

### Multiplicación de matrices

In [ ]:
tensor_1.matmul(tensor_2)

tensor([[7390, 4294],
        [6265, 4396]])

In [ ]:
tensor_1 @ tensor_2

tensor([[7390, 4294],
        [6265, 4396]])

## Obtener la transpuesta

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = torch.tensor(value)

In [ ]:
value_as_tensor.transpose(0, 2)

tensor([[[21, 56],
         [35, 64]],

        [[83, 98],
         [12, 78]],

        [[42, 24],
         [67, 98]]])

## Obtener la inversa

In [ ]:
value = [[21, 83],
         [35, 12]]
value_as_tensor = torch.tensor(value, dtype=torch.float32)

In [ ]:
value_as_tensor.inverse()

tensor([[-0.0045,  0.0313],
        [ 0.0132, -0.0079]])

## Obtener la cantidad de elementos

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = torch.tensor(value)

#Number of elements
value_as_tensor.numel()

12

## Obtener el mayor elemento y su índice

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = torch.tensor(value)

In [ ]:
value_as_tensor.max(dim=0)

torch.return_types.max(values=tensor([[56, 98, 42],
        [64, 78, 98]]), indices=tensor([[1, 1, 0],
        [1, 1, 1]]))

In [ ]:
value_as_tensor.max(dim=1)

torch.return_types.max(values=tensor([[35, 83, 67],
        [64, 98, 98]]), indices=tensor([[1, 0, 1],
        [1, 0, 1]]))

In [ ]:
value_as_tensor.max(dim=2)

torch.return_types.max(values=tensor([[83, 67],
        [98, 98]]), indices=tensor([[1, 2],
        [1, 2]]))

In [ ]:
value_as_tensor.max(dim=-1) #-1: last_possible_axis

torch.return_types.max(values=tensor([[83, 67],
        [98, 98]]), indices=tensor([[1, 2],
        [1, 2]]))

In [ ]:
value_as_tensor.max(dim=-1).values

tensor([[83, 67],
        [98, 98]])

In [ ]:
value_as_tensor.max(dim=-1).indices

tensor([[1, 2],
        [1, 2]])

## Indexación

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = torch.tensor(value)

In [ ]:
value_as_tensor[0]

tensor([[21, 83, 42],
        [35, 12, 67]])

In [ ]:
value_as_tensor[1]

tensor([[56, 98, 24],
        [64, 78, 98]])

In [ ]:
value_as_tensor[0:1]

tensor([[[21, 83, 42],
         [35, 12, 67]]])

In [ ]:
value_as_tensor[1:2]

tensor([[[56, 98, 24],
         [64, 78, 98]]])

In [ ]:
value_as_tensor[0, 0]

tensor([21, 83, 42])

In [ ]:
value_as_tensor[0, 1]

tensor([35, 12, 67])

In [ ]:
value_as_tensor[:, 0]

tensor([[21, 83, 42],
        [56, 98, 24]])

In [ ]:
value_as_tensor[:, 1]

tensor([[35, 12, 67],
        [64, 78, 98]])

In [ ]:
value_as_tensor[0, 0, 0]

tensor(21)

In [ ]:
value_as_tensor[0, 0, 1]

tensor(83)

In [ ]:
value_as_tensor[0, 0, 2]

tensor(42)

In [ ]:
value_as_tensor[:, :, 0]

tensor([[21, 35],
        [56, 64]])

In [ ]:
value_as_tensor[:, :, 1]

tensor([[83, 12],
        [98, 78]])

In [ ]:
value_as_tensor[:, :, 2]

tensor([[42, 67],
        [24, 98]])

## Manipulando *Shapes*

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_tensor = torch.tensor(value)

value_as_tensor.shape

torch.Size([2, 2, 3])

In [ ]:
value_as_tensor.reshape((12,))

tensor([21, 83, 42, 35, 12, 67, 56, 98, 24, 64, 78, 98])

In [ ]:
value_as_tensor.reshape((2, 6))

tensor([[21, 83, 42, 35, 12, 67],
        [56, 98, 24, 64, 78, 98]])

In [ ]:
value_as_tensor.reshape((4, 3))

tensor([[21, 83, 42],
        [35, 12, 67],
        [56, 98, 24],
        [64, 78, 98]])

In [ ]:
value_as_tensor.reshape((3, 4))

tensor([[21, 83, 42, 35],
        [12, 67, 56, 98],
        [24, 64, 78, 98]])

In [ ]:
value_as_tensor.reshape((-1,))

tensor([21, 83, 42, 35, 12, 67, 56, 98, 24, 64, 78, 98])

In [ ]:
value_as_tensor.reshape((3, -1))

tensor([[21, 83, 42, 35],
        [12, 67, 56, 98],
        [24, 64, 78, 98]])

## Convertir Tensores a NumPy array

In [ ]:
value = [21, 83, 42, 35]
value_as_tensor = torch.tensor(value)

In [ ]:
value_as_tensor.numpy()

array([21, 83, 42, 35])

In [ ]:
np.array(value_as_tensor)

array([21, 83, 42, 35])

# Ejercicio

## NumPy

In [ ]:
import numpy as np

np.random.seed(0)

In [ ]:
x = np.arange(100)/100
y = x + np.random.normal(scale=0.05, size=100)

In [ ]:
#Agregamos 1's en la primera columna al arreglo de x
x = np.array([np.array([1, i]) for i in x])

In [ ]:
y = y.reshape((-1, 1))

Calcular $ z = (x^{T} x)^{-1} x^{T}y $

## TensorFlow

In [ ]:
import tensorflow as tf
import numpy as np

np.random.seed(0)

In [ ]:
x = np.arange(100)/100
y = x + np.random.normal(scale=0.05, size=100)

In [ ]:
#Agregamos 1's en la primera columna al arreglo de x
x = np.array([np.array([1, i]) for i in x])

In [ ]:
y = y.reshape((-1, 1))

Calcular $ z = (x^{T} x)^{-1} x^{T}y $

## PyTorch

In [ ]:
import torch
import numpy as np

np.random.seed(0)

In [ ]:
x = np.arange(100)/100
y = x + np.random.normal(scale=0.05, size=100)

In [ ]:
#Agregamos 1's en la primera columna al arreglo de x
x = np.array([np.array([1, i]) for i in x])

In [ ]:
y = y.reshape((-1, 1))

Calcular $ z = (x^{T} x)^{-1} x^{T}y $